org: luizcalaca
app: aws-typescript-project-read-csv-ai
service: aws-typescript-project-read-csv-ai
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/index.handler
    events:
      - s3:
          bucket: aws-node-express-api-proj-serverlessdeploymentbuck-y0rzb4xzhqe23
          event: s3:ObjectCreated:*
