org: luizcalaca
app: aws-typescript-project-read-csv-ai
service: aws-typescript-project-read-csv-ai
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/index.handler
    events:
      - s3:
          bucket: "arn:aws:s3:::${file(config.json):S3_BUCKET_NAME}/*"
          event: s3:ObjectCreated:*
